# Generated by Django 5.0.4 on 2025-03-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
            ],
        ),
    ]
